### ISSUE TITLE
Write proper Documentation in files.

### ISSUE THREAD

**Issue by priyankabehera** [prajapatisagar/Live-It-Up#1]
Hello @prajapatisagar 

There is blank DocComment in `Theme URI:`. Check in below URL:
https://github.com/prajapatisagar/Live-It-Up/blob/master/style.css#L3

Recommended the https://github.com/prajapatisagar/Live-It-Up URL in the `Theme URI:` section.

Cheers!

**Comment by prajapatisagar** [comment]
Solved
